### ISSUE TITLE
Dualis-Bot mit Telegram Benachrichtigungen

### ISSUE THREAD

**Issue by lumaghg** [michael-spengler/wwi20sea-web-programmierung#2]
Ich will einen Crawler bauen, der uns Studenten eine Telegramnachricht schickt, wenn es neue Noten in Dualis (Notenportal) gibt.
Aus organisatorischen Gründen suche ich zusätzlich zu mir noch einen Backendentwickler, einen Frontendentwickler und einen UI-Designer.

**Comment by STAT1C-Sy** [comment]
da seh ich mich

**Comment by steffenhls** [comment]
Wäre für Frontend down

**Comment by MaikKBRNK** [comment]
Hey ich bin dabei. Hab mal mit Paint designt.

**Comment by lumaghg** [comment]
Gut, dann haben wir ja genug :-)

**Comment by lumaghg** [comment]
Klingt nach nem Plan :)

**Comment by lumaghg** [comment]
Dann Robin, Steffen, Maik und Fynn

**Comment by lumaghg** [comment]
https://github.com/dualis-bot/backend
