### ISSUE TITLE
Social Media Analytics Tool

### ISSUE THREAD

**Issue by MatthiasBiermanns** [michael-spengler/wwi20sea-web-programmierung#4]
Auf der Seite könnte man Bspw. einen Username eingeben, dazu werden dann relevante Statistiken angezeigt

**Comment by TobiasFitzke01** [comment]
Find ich cool, bin dabei

**Comment by michael-spengler** [comment]
https://www.youtube.com/watch?v=joys6F5tcio&feature=youtu.be

**Comment by HaseFlrn** [comment]
very interesting

**Comment by michael-spengler** [comment]
https://github.com/timonpitz/EasyInsta

**Comment by MatthiasBiermanns** [comment]
Top also 5 Leute:
Rebekka, Florian, Lea, Tobias und Matthias

**Comment by HaseFlrn** [comment]
[Unser Repo](https://github.com/HaseFlrn/social-media-service)
